### ISSUE TITLE
NME score and models underhood

### ISSUE THREAD

**Issue by gordinmitya** [atksh/onnx-facial-lmk-detector#1]
Hello,
Is this a combination of existing detection + landmarks models? Could you share names if so?
And have you measured NME score on some public datasets? (eg WFLW)
Thank you!

**Comment by atksh** [comment]
Hello, thanks for asking.

> Is this a combination of existing detection + landmarks models? Could you share names if so?

I've updated README.md and would appreciate it if you could check it.

> And have you measured NME score on some public datasets? (eg WFLW)

No, but it should be equivalent to the score of 2d106det.

**Comment by gordinmitya** [comment]
Couldn't expect such fast answer, thank you for the details!
