### ISSUE TITLE
Pytorch code

### ISSUE THREAD

**Issue by omair18** [atksh/onnx-facial-lmk-detector#2]
Can you also share the pytorch code for the following parts?

- Estimate the norm and apply an affine transformation to each face.
- Crop the faces and resize them to (192, 192).
- Process the predicted landmarks and apply the inverse affine transform to each face.

**Comment by atksh** [comment]
Thank you for your interest.

I have committed the code to [src](https://github.com/atksh/onnx-facial-lmk-detector/tree/main/src).
